### ISSUE TITLE
Source code check ?

### ISSUE THREAD

**Issue by yves-chevallier** [heig-tin-info/baygon#21]
Add feature to : 

- Parse source code and automatically
  - [ ] Detect code in comments
  - [ ] Program Header
  - [ ] Header reentrance protection
  - [ ] Grep line/code
  - [ ] "lint" c Code
  - [ ] Verify indentation
  - [ ] Code length
- Documentation
  - [ ] How to install or contribute?
- Unit tests?
  
  ```yaml
  tests: 
    - name: Test function sum
      function: sum(3, 4)
      return: 7
  ```
- ID

   ```yaml
   tests: 
     - name: Test 
       id: test_a
   ```
- Output json/yaml

   ```sh
   $ baygon --yaml
   ```
