### ISSUE TITLE
Loops ? 

### ISSUE THREAD

**Issue by yves-chevallier** [heig-tin-info/baygon#22]
I propose a new feature that can:

1. Use variables in tests
2. Can do multiple iterations on the same test (repeat it)

Here are some examples written with Baygon YAML:

```yaml
filters:
  eval: true # Evaluation of inside variables
  executable: 'perl'
tests:
  - name: Use of variables
    args: ['-e', 'print $ARGV[0] + 42', '{{i = randint(0, 100)}}']
    exit: '{{i + 42}}'
  - name: Loop
    args: ['-e', 'print $ARGV[0] + $ARGV[1]', '{{i = randint(0, 100)}}', '{{i = randint(0, 100)}}']
    iterations: 10
    exit: '{{i + j}}'    
  - name: Iteration
    args: ['-e', 'print $ARGV[0] + $ARGV[1]', '{{i = Iter(0, 1)}}', '{{i = Iter(100, -2)}}']
    iterations: 100
    exit: '{{i + j}}'
  - name: Complex operations
    args: 
      - '-e'
      - 'print -($ARGV[1] * sqrt($ARGV[1] * $ARGV[1] - 4 * $ARGV[0] * $ARGV[2])) / (2 * $ARGV[0])'
      - '{{a = rand(0, 100)}}'
      - '{{b = rand(0, 100)}}'
      - '{{c = rand(0, -100)}}'
    iterations: 100
    exit: '{{-b + sqrt(b * b - 4 * a * c) / (2 * a)}}'
```

The syntax would evaluate any mustache (placeholder) `{{}}` with Python. These placeholders should be modifiable with the `eval: {open: '{{', close: '}}'}` directive. By default the following packages should be included:

- `from math import *`
- `from random import randint, random`

For a variable assignment, the mustache returns the value: `{{i = 42}}` would return the value of `_ = i = 42`, which is 42. 

In addition, to loops, some functions could memorize states from the previous iteration. An `Iter` instance can behave like a number, but its value is incremented between each call. 

```python
class Iter(Number, Iterable):
   def __init__(self, start=0, increment=1):
      self.value = start
      self.increment = increment
   def __int__(self):
      return self.value
   def __str__(self): 
      return str(self.value)
   def __repr__(self):
      return f"Iter<{str(self)}>"
   def __next__(self):
      self.value += self.increment
   def __iter__(self):
       while(True):
           yield self.value 
           next(self)
```

More helper functions could be implemented in a future version of Baygon. 

The goal is to `eval` the inside Python code in a sandbox that lives only during a test. The context is kept for all iterations of the same test.
