### ISSUE TITLE
Additional match criteria

### ISSUE THREAD

**Issue by yves-chevallier** [heig-tin-info/baygon#27]
Currently only `contains`, `regex`, `equals` are available. I propose some additional matchers for numbers: 

```yaml
- number: 12.32
- number: 
    value: 12.23 # Expected number
    precision: 0.1 # plus minus
    lt: # less than
    le: # less or equal
    bt: # bigger than
    be: # bigger or equal
    min: 
    max:
- length: 4
- length: 
    min: 4
    max: 12
```
