### ISSUE TITLE
Allow execute program to feed in another

### ISSUE THREAD

**Issue by yves-chevallier** [heig-tin-info/baygon#30]
```yaml
- name: Test feed in
  stdin:
    repeat: 10
    executable: ./generate
    args: ['-s{{i++}}']
  stdout: 
    - contains: '{{i}}'
```
